### ISSUE TITLE
SINTESIS CALIDAD

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-carlos-chrs#1]
[sintesis_carlos_C.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-carlos-chrs/files/9601405/sintesis_carlos_C.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
